---
title: "Project 2"
authors: "Navdeep Singh, Shreya Khobragade, Samridhi Hooda"
output: html_notebook
---

```{r load_libraries}
#loading all the necessary libraries
library(gutenbergr)
library(tidytext)
library(tidyverse)
library(readtext)
library(sentimentr)
library(ggiraphExtra)
library(ggplot2)
library(RColorBrewer)
library(scales)
```

```{r gutenberg_fitzgerald_works}
#finding texts by Fitzgerald on gutenberg
fitzgerald_text <- gutenberg_works(author == "Fitzgerald, F. Scott (Francis Scott)")
fitzgerald_text <- fitzgerald_text[-c(2,3), ]
```

```{r gutenberg_fitzgerald_download}
#downloading all the texts found
fitzgerald_download <- fitzgerald_text %>% 
                      gutenberg_download(meta_fields = c("title", "author"))
```
```{r import_Fitzgerald_books}
The_Great_Gatsby <- read_delim("The Great Gatsby_Fitzgerald, F. Scott (Francis Scott)_clean.txt", 
    delim = ".", quote = "\\\"", escape_double = FALSE)
The_Great_Gatsby <- The_Great_Gatsby %>% mutate(author = "Fitzgerald, F. Scott (Francis Scott)", .after = text) %>% mutate(title = "The Great Gatsby", .before = author)

Tender_is_the_Night <- read_delim("Tender is the Night_Fitzgerald, F. Scott (Francis Scott)_clean.txt", 
    delim = ".", quote = "\\\"", escape_double = FALSE)
Tender_is_the_Night <- Tender_is_the_Night %>% mutate(author = "Fitzgerald, F. Scott (Francis Scott)", .after = text) %>% mutate(title = "Tender is the Night", .before = author)
```

```{r create_Fitzgerald_corpus}
fitzgerald_download$gutenberg_id <- NULL
fitzgerald_corpus <- bind_rows(fitzgerald_download, The_Great_Gatsby, Tender_is_the_Night)
```


```{r import_Hemingway_books}

The_Sun_Also_Rises_Hemingway_Ernest <- read_delim("The Sun Also Rises_Hemingway, Ernest_clean.txt", 
    delim = "\t", quote = "\\\"", escape_double = FALSE, 
    trim_ws = TRUE)
The_Sun_Also_Rises_Hemingway_Ernest <- The_Sun_Also_Rises_Hemingway_Ernest %>% mutate(author = "Hemingway, Earnest", .after = text) %>% mutate(title = "The Sun Also Rises", .before = author)

The_Old_Man_and_the_Sea_Hemingway_Ernest <- read_delim("The Old Man and the Sea_Hemingway, Ernest_clean.txt", 
    delim = ".", quote = "\\\"", escape_double = FALSE)
The_Old_Man_and_the_Sea_Hemingway_Ernest <- The_Old_Man_and_the_Sea_Hemingway_Ernest %>% mutate(author = "Hemingway, Earnest", .after = text) %>% mutate(title = "The Old Man and the Sea", .before = author)

For_Whom_the_Bell_Tolls_Hemingway_Ernest <- read_delim("For Whom the Bell Tolls_Hemingway, Ernest_clean.txt", 
    delim = ".", quote = "\\\"", escape_double = FALSE)
For_Whom_the_Bell_Tolls_Hemingway_Ernest <- For_Whom_the_Bell_Tolls_Hemingway_Ernest %>% mutate(author = "Hemingway, Earnest", .after = text) %>% mutate(title = "For Whom The Bell Tolls", .before = author)

A_Farewell_to_Arms_Hemingway_Ernest <- read_delim("A Farewell to Arms_Hemingway, Ernest_clean.txt", 
    delim = ".", quote = "\\\"", escape_double = FALSE)
A_Farewell_to_Arms_Hemingway_Ernest <- A_Farewell_to_Arms_Hemingway_Ernest %>% mutate(author = "Hemingway, Earnest", .after = text) %>% mutate(title = "A Farewell to Arms", .before = author)

The_Garden_of_Eden_Hemingway <- read_delim("The Garden of Eden_Hemingway_clean.txt", 
    delim = "\t", quote = "\\\"", escape_double = FALSE, 
    trim_ws = TRUE)
The_Garden_of_Eden_Hemingway_Ernest <- The_Garden_of_Eden_Hemingway %>% mutate(author = "Hemingway, Earnest", .after = text) %>% mutate(title = "The Garden of Eden", .before = author)

hemingway_corpus <- bind_rows(The_Sun_Also_Rises_Hemingway_Ernest,The_Old_Man_and_the_Sea_Hemingway_Ernest,For_Whom_the_Bell_Tolls_Hemingway_Ernest,A_Farewell_to_Arms_Hemingway_Ernest,The_Garden_of_Eden_Hemingway_Ernest)
```

```{r new_sentiment_analysis}
#temp <- hemingway_corpus %>% unnest_regex(sentences, text, pattern = "[.?!]", to_lower = TRUE)
my_text <- read_file("~/Digital.Humanities/dh_proj_2/The Garden of Eden_Hemingway_clean.txt")
my_text <- get_sentences(my_text)
new_text <- c(my_text)
total_sentiment <- sentiment(my_text)
total <- sum(total_sentiment$sentiment)
```


```{r all_authors}
all_authors <- bind_rows(fitzgerald_corpus, hemingway_corpus)

```

```{r tidy_all_authors}
tidy_all_authors <- all_authors %>% unnest_tokens(word, text) %>% anti_join(stop_words)
```


```{r tidy_hemingway}
#breaking up texts into words
tidy_eden <- The_Garden_of_Eden_Hemingway_Ernest %>% unnest_tokens(word, text) %>% anti_join(stop_words)
tidy_hemingway <- hemingway_corpus %>% unnest_tokens(word, text) %>% anti_join(stop_words)
```

```{r tidy_fitzgerald}
#breaking up texts into words
tidy_gatsby <- The_Great_Gatsby %>% unnest_tokens(word, text) %>% anti_join(stop_words)
tidy_fitzgerald <- fitzgerald_corpus %>% unnest_tokens(word, text) %>% anti_join(stop_words)
```

```{r sentiment_nrc}
nrc_list <- get_sentiments("nrc")
counter <- tidy_hemingway %>% inner_join(nrc_list) %>% count(word, sort = TRUE)
sentiment_h <- tidy_hemingway %>% inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("anger", 
                                         "anticipation", "disgust", "fear", "joy", "sadness", "surprise", "trust"))
    ) %>%
  count(sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% mutate(author = "Hemingway")#%>% 
  #mutate(sentiment = positive - negative)
sentiment_h3 <- tidy_eden %>% inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("anger", 
                                         "anticipation", "disgust", "fear", "joy", "sadness", "surprise", "trust"))
    ) %>%
  count(sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% mutate(author = "Hemingway")
sentiment_h2 <- sentiment_h[,-9]/126688
sentiment_h2 <- sentiment_h2*100
sentiment_h2 <- sentiment_h2 %>% mutate(author = "Hemingway")
#anger	anticipation	disgust	fear	joy	sadness	surprise	trust
```

```{r}
nrc_joy <- get_sentiments("nrc")
#tidy_hemingway %>% inner_join(nrc_list) %>% count(word, sort = TRUE)
sentiment_f <- tidy_fitzgerald %>% inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("anger", 
                                         "anticipation", "disgust", "fear", "joy", "sadness", "surprise", "trust"))
    ) %>%
  count(sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% mutate(author = "Fitzgerald")
sentiment_f3 <- tidy_gatsby %>% inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("anger", 
                                         "anticipation", "disgust", "fear", "joy", "sadness", "surprise", "trust"))
    ) %>%
  count(sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% mutate(author = "Fitzgerald")
sentiment_f2 <- sentiment_f[,-9]/134829
sentiment_f2 <- sentiment_f2*100
sentiment_f2 <- sentiment_f2 %>% mutate(author = "Fitzgerald")
```

```{r}
sentiment_table <- bind_rows(sentiment_h, sentiment_f)
#sentiment_table2 <- bind_rows(sentiment_f3, sentiment_h3)
ggRadar(
  data = sentiment_table,
  mapping = aes(color = author),
  rescale = FALSE,
  interactive = TRUE,
  use.label = TRUE,
  size = 2,
  legend.position = "right"
)
```
```{r}
ggplot(data=sentiment_table, aes(x=anger, y=anticipation, fill=author)) +
  geom_bar(stat="identity")

```

```{r adding_female_words}
#collection of words representing a female
female_words <- c("she", "her", "woman", "girl", "aunt", "mother", "sister", "wife", "lady")

female_df <- tibble(word = female_words, female = TRUE)
```

```{r hemingway_tagged}
hemingway_tagged <- tidy_hemingway %>% left_join(female_df)
```

```{r fitzgerald_tagged}
fitzgerald_tagged <- tidy_fitzgerald %>% left_join(female_df)
```

```{r fitzgerald_count}
#counting how often female words appeared
#table shows each text and the respective percentage
fitzgerald_table <- fitzgerald_tagged %>% group_by(title) %>% count(female) %>% mutate(percent = n/sum(n)*100)

```

```{r hemingway_count}
#counting how often female words appeared
#table shows each text and the respective percentage
hemingway_table <- hemingway_tagged %>% group_by(title) %>% count(female) %>% mutate(percent = n/sum(n)*100)

```

```{r combined_result}
#table showing two authors and their respective usage of female words
author_table <- bind_rows(fitzgerald_tagged, hemingway_tagged)
author_table <- author_table %>% group_by(author) %>% count(female) %>% mutate(percent = n/sum(n)*100) %>% drop_na(female)

#table showing all texts and their respective usage of female words
combined_table <- bind_rows(hemingway_table, fitzgerald_table) %>% drop_na(female)
```
```{r frequency_distribution}
hemingway_wordcount <- tidy_hemingway %>% count(word, sort = TRUE) %>% mutate(frequency = (n/sum(n)), .after = n)
fitzgerald_wordcount <- tidy_fitzgerald %>% count(word, sort = TRUE) %>% mutate(frequency = (n/sum(n)), .after = n)

```

```{r emotion_words}
emotion_list <- read_csv("emotion_list.txt")
emotion_words <- tibble(emotion_list, emotion = TRUE)
```

```{r hemingway_emotions}
hemingway_emotions <- tidy_hemingway %>% left_join(emotion_words)
```

```{r fitzgerald_emotions}
fitzgerald_emotions <- tidy_fitzgerald %>% left_join(emotion_words)
```

```{r fitzgerald_emotion_table}
#counting how often female words appeared
#table shows each text and the respective percentage
fitzgerald_emotion_calc <- fitzgerald_emotions %>% group_by(title) %>% count(emotion) %>% mutate(percent = n/sum(n)*100) %>% mutate(author = "F. Scott Fitzgerald")

```

```{r hemingway_emotion_table}
#counting how often female words appeared
#table shows each text and the respective percentage
hemingway_emotion_calc <- hemingway_emotions %>% group_by(title) %>% count(emotion) %>% mutate(percent = n/sum(n)*100) %>% mutate(author = "Earnest Hemingway")

```

```{r emotion_plot}
combined_table <- bind_rows(hemingway_emotion_calc, fitzgerald_emotion_calc) %>% filter(emotion == TRUE)

p<-ggplot(data=combined_table, aes(x=percent, y=title, fill=author)) +
  geom_bar(stat="identity")
p
```

## Sentiment Analysis

```{r all_author_sentences}
all_authors_sentence <- all_authors %>%
  group_by(author, title, text) %>%
  summarise (text = paste(text, collapse = "")) %>%
  unnest_regex(sentences, text, pattern = "[.?!]", to_lower = TRUE)  
```

```{r author_sentence_nr}
author_sentence_nr <- all_authors_sentence %>%
  ungroup() %>%
  mutate(sentence_number = row_number()) %>%
  group_by(author, title, sentence_number) %>%
  unnest_tokens(word, sentences) %>%
  anti_join(stop_words)
```

```{r author_concept}
author_concept <-  author_sentence_nr #%>%
  #left_join(emotion_words) 
```

```{r author_concept_sentiment}
author_concept_sentiment <- author_concept %>%
  inner_join(get_sentiments("bing"))
```

```{r author_sentiment_total}
author_sentiment_total <- author_concept_sentiment %>%
  count(sentence_number, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0)  %>%
  mutate(sentiment = positive - negative) #%>%
  #left_join(author_concept) #%>%
  #filter(emotion == TRUE)
```

```{r author_sentiment_table}
author_sentiment_table <- author_sentiment_total %>%
  #pivot_longer(sentiment,
               #names_to = "word",
               #values_to = "total_sentiment")  %>%
  #drop_na() %>%
  group_by(title, author) %>%
  summarise (total = sum(sentiment)) %>%
  ungroup()
```

```{r author_sentiment_plot}
author_sentiment_table %>%
  ggplot(aes(title, y = total, fill = title)) +
  geom_col(color = "black",
           alpha = .7,
           position = "identity") +
  #facet_wrap(~ concept) +
  labs(title = "Positive and Negative Sentiment by Concept",
       x = "Overal Sentiment",
       y = "Author",
       fill = "Title") +
  coord_flip() 
```

```{r exporting_tables}
save(author_table, hemingway_corpus, file = "saved_data.rda")
```



```{r wildcard}
puretext <- bind_rows(tidy_hemingway[, 3], tidy_fitzgerald[, 3])
purestring <- unlist(puretext)
sad_1 <- paste(unique(str_subset(purestring, "^anger|^angr|^disgust|^contempt|^revuls|^envy|^envi|^jealous|^exaspera|^frustra|^aggrava|^agitat|^annoy|^grouch|^grump|^irrita|^bitter|^dislike|^feroci|^fury|^furi|^hate|^hostil|^loath|^outrage|^rage|^rag|^resent|^scorn|^spite|^venge|^wrath|^torment|^fear|^horr|^alarm|^fright|^hyster|^mortifi|^panic|^shock|^terror|^nervous|^anxi|^apprehen|^distress|^dread|^tense|^uneasi|^uneasy|^worr|^joy|^cheer|^amuse|^bliss|^delight|^ecsta|^elati|^enjoy|^euphor|^gaiety|^glad|^glee|^happi|^jolli|^jolly|^jovial|^jubil|^satisf|^content|^pleasur|^enthrall|^raptur|^eager|^hope|^optimis|^pride|^proud|^triumph|^relie|^zest|^enthusias|^excit|^exhilara|^thrill|^zeal|^love|^ador|^affec|^attrac|^care|^cari|^compassion|^fond|^like|^liking|^sentiment|^tender|^long|^arous|^desire|^infatuat|^lust|^passion|^sad|^disappoint|^dismay|^displeasur|^alien|^defeat|^deject|^embarrass|^homesick|^humiliat|^insecur|^isola|^insult|^lonel|^neglect|^reject|^depress|^despair|^gloom|^glum|^grie|^hopeless|^melancholi|^miser|^sorrow|^unhappi|^woe|^shame|^guilt|^regret|^remorse|^suffer|^agon|^anguish|^hurt|^pity|^piti|^sympath|^surprise|^amaze|^astonish")), collapse = ' ')
```